# 행렬의 두 얼굴 — 데이터를 담는 표, 공간을 바꾸는 장치 (행렬 곱셈이 쉬워지는 법)

**Zero to 머신러닝 딥러닝 Master — Medium 시리즈 #13** · 원문: 책 01-04 「행렬 — 숫자를 표로 정리하기」

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/otoloism/Zero_to_ML_Master/blob/main/medium-series/13-matrix-basics/13_matrix_basics.ipynb)

행렬을 "데이터를 담는 표"와 "벡터를 바꾸는 함수" 두 얼굴로 보고, 행렬×벡터를 행 내적·열 가중합 두 관점으로 계산합니다. AB ≠ BA 를 회전·전단 변환으로 확인하고, 연립방정식·역행렬·전치, 그리고 신경망 순전파 XW 의 shape 설계까지 실행합니다.

- 📝 Medium 글: **TODO: Medium 게시 후 URL 입력** (`https://medium.com/p/...`)
- 📘 책 원문: [01-04 행렬 — 숫자를 표로 정리하기](https://wikidocs.net/439753)
- 🏠 [mldict.net](https://mldict.net) · ✍️ [기술 블로그](https://wikidocs.net/blog/@mldict/) · 📚 [책 전체 목차](https://wikidocs.net/book/21464)

## 1. 1단계 — 첫 번째 얼굴: 행렬은 표다

학생×특성 표를 행렬로 만들고 shape·인덱싱·행/열 슬라이싱을 확인합니다.

In [1]:
import numpy as np

X = np.array([[175, 70, 25],      # 1행: 학생1 (키, 몸무게, 나이)
              [162, 55, 22],      # 2행: 학생2
              [180, 78, 30]])     # 3행: 학생3

print("행렬 X:\n", X)
print("모양(shape):", X.shape, "→ 3행 3열")
print("X[1, 0] =", X[1, 0], "(2번째 학생의 키)")
print("2번째 행 전체 =", X[1])
print("1번째 열 전체 =", X[:, 0])

행렬 X:
 [[175  70  25]
 [162  55  22]
 [180  78  30]]
모양(shape): (3, 3) → 3행 3열
X[1, 0] = 162 (2번째 학생의 키)
2번째 행 전체 = [162  55  22]
1번째 열 전체 = [175 162 180]


## 2. 1.5단계 — 행렬 = 함수

숫자 함수 f(x)=4x 와, 벡터를 받아 벡터를 돌려주는 행렬 A 를 비교합니다.

In [2]:
import numpy as np

# ── 1차원: 숫자를 받아 숫자를 돌려주는 함수 ──
def f(x):
    return 4 * x            # 규칙: 4를 곱한다

print("f(3) =", f(3))       # 숫자 → 숫자
print("f(5) =", f(5))

# ── 행렬: 벡터를 받아 벡터를 돌려주는 함수 ──
A = np.array([[2, 0],
              [0, 3]])      # 규칙: x는 2배, y는 3배

벡터 = np.array([1, 1])
print("A @ 벡터 =", A @ 벡터)   # 벡터 → 벡터

# 규칙(A)은 그대로, 입력만 바꿔 본다
print("A @ [2,1] =", A @ np.array([2, 1]))
print("A @ [0,4] =", A @ np.array([0, 4]))

f(3) = 12
f(5) = 20
A @ 벡터 = [2 3]
A @ [2,1] = [4 3]
A @ [0,4] = [ 0 12]


## 3. 3단계 — 덧셈과 스칼라곱 (원소별 곱 vs 행렬 곱)

A + B, 2A, A * B, A @ B 의 차이를 확인합니다.

In [3]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A + B =\n", A + B)
print("2 * A =\n", 2 * A)
print("A * B (원소별 곱) =\n", A * B)
print("A @ B (행렬 곱) =\n", A @ B)

A + B =
 [[ 6  8]
 [10 12]]
2 * A =
 [[2 4]
 [6 8]]
A * B (원소별 곱) =
 [[ 5 12]
 [21 32]]
A @ B (행렬 곱) =
 [[19 22]
 [43 50]]


## 4. 읽는 법 ② — 행렬×벡터의 두 관점

행 내적 관점과 열 가중합 관점이 NumPy 결과와 같은지 확인합니다.

In [4]:
import numpy as np

M = np.array([[2, 0],
              [1, 3]])
v = np.array([1, 2])

# 관점 1 — 행과 벡터의 내적
row_view = np.array([np.dot(M[0], v), np.dot(M[1], v)])

# 관점 2 — 열들의 가중합 (v의 성분이 각 열에 곱해짐)
col_view = v[0] * M[:, 0] + v[1] * M[:, 1]

print("관점 1 (행 내적)   :", row_view)
print("관점 2 (열 가중합) :", col_view)
print("NumPy 결과         :", M @ v)
print("세 결과가 모두 같은가?", np.array_equal(row_view, col_view) and np.array_equal(col_view, M @ v))

관점 1 (행 내적)   : [2 7]
관점 2 (열 가중합) : [2 7]
NumPy 결과         : [2 7]
세 결과가 모두 같은가? True


## 5. 6단계 — 왜 AB ≠ BA 인가

행렬 곱의 순서를 바꾸고, 회전·전단 변환의 합성 순서에 따라 결과가 달라지는 것을 봅니다.

In [5]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A @ B =\n", A @ B)
print("B @ A =\n", B @ A)
print("두 결과가 같은가?", np.array_equal(A @ B, B @ A))

R = np.array([[0, -1], [1, 0]])      # 90도 회전
S = np.array([[1,  1], [0, 1]])      # 전단(기울이기)
print("\n전단 먼저, 회전 나중 (R @ S) =\n", R @ S)
print("회전 먼저, 전단 나중 (S @ R) =\n", S @ R)

A @ B =
 [[19 22]
 [43 50]]
B @ A =
 [[23 34]
 [31 46]]
두 결과가 같은가? False

전단 먼저, 회전 나중 (R @ S) =
 [[ 0 -1]
 [ 1  1]]
회전 먼저, 전단 나중 (S @ R) =
 [[ 1 -1]
 [ 1  0]]


## 6. 7단계 — 연립방정식·역행렬·전치

np.linalg.solve 로 해를 구하고 역행렬·단위행렬·전치를 확인합니다.

In [6]:
import numpy as np

# 연립방정식   2x +  y = 5
#              x + 3y = 10
M = np.array([[2, 1],
              [1, 3]])
b = np.array([5, 10])

sol = np.linalg.solve(M, b)                # Mv = b 를 푸는 함수
print("해 (x, y) =", sol)
print("검산 M @ sol =", M @ sol, "→ b와 같은가?", np.allclose(M @ sol, b))

M_inv = np.linalg.inv(M)                   # 역행렬
print("\n역행렬 M⁻¹ =\n", M_inv)
print("M⁻¹ @ M =\n", np.round(M_inv @ M, 10), "← 단위행렬")
print("\n전치 M.T =\n", M.T)

해 (x, y) = [1. 3.]
검산 M @ sol = [ 5. 10.] → b와 같은가? True

역행렬 M⁻¹ =
 [[ 0.6 -0.2]
 [-0.2  0.4]]
M⁻¹ @ M =
 [[ 1. -0.]
 [ 0.  1.]] ← 단위행렬

전치 M.T =
 [[2 1]
 [1 3]]


## 7. 8단계 — ML에서의 행렬: 순전파와 배치 shape

입력 1개와 배치 4개에 가중치 W 를 곱해 shape 변화를 확인합니다.

In [7]:
import numpy as np

W = np.array([[0.5, 0.2],      # 입력1 → 출력1, 출력2
              [0.3, 0.8],      # 입력2 → 출력1, 출력2
              [0.1, 0.4]])     # 입력3 → 출력1, 출력2

x = np.array([1, 2, 3])                    # 데이터 1개 (3차원)
print("입력 1개 :", x.shape, "@", W.shape, "→", (x @ W).shape)
print("출력      :", x @ W)

X = np.array([[1, 2, 3],                   # 데이터 4개를 한 번에 (배치)
              [2, 0, 1],
              [0, 1, 4],
              [3, 3, 3]])
print("\n배치 4개 :", X.shape, "@", W.shape, "→", (X @ W).shape)
print("출력      :\n", np.round(X @ W, 2))

입력 1개 : (3,) @ (3, 2) → (2,)
출력      : [1.4 3. ]

배치 4개 : (4, 3) @ (3, 2) → (4, 2)
출력      :
 [[1.4 3. ]
 [1.1 0.8]
 [0.7 2.4]
 [2.7 4.2]]


## 🔗 함께 보기

- 📘 **책 (WikiDocs)** — [Zero to 머신러닝 딥러닝 Master](https://wikidocs.net/book/21464)
- 🏠 **홈페이지** — [mldict.net](https://mldict.net)
- ✍️ **기술 블로그** — [wikidocs.net/blog/@mldict](https://wikidocs.net/blog/@mldict/)
- 💻 **전체 코드 저장소** — [github.com/otoloism/Zero_to_ML_Master](https://github.com/otoloism/Zero_to_ML_Master)

👉 더 자세한 설명과 그림은 [책 원문](https://wikidocs.net/439753) 에서 확인하세요.